name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  env:
    working-directory: ./money_matters
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{env.working-directory}}
      - name: Build web app
        run: flutter build web #--release --web-renderer=html
        working-directory: ${{env.working-directory}}

      - uses: actions/upload-artifact@v3
        with:
          name: flutter-app
          path: build/web/
          working-directory: ${{env.working-directory}}