name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Build web app
        run: flutter build web --release --web-renderer=html

      - uses: actions/upload-artifact@v3
        with:
          name: flutter-app
          path: build/web/ # or path/to/artifact